spring.application.name=dropcrate-web

# Local PostgreSQL from docker/compose.yaml
spring.datasource.url=jdbc:postgresql://localhost:15432/dropcrate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=dropcrate
spring.datasource.password=dropcrate

spring.jpa.hibernate.ddl-auto=none

# Local basic auth for default Spring Security.
spring.security.user.name=dropcrate
spring.security.user.password=dropcrate
